spring:
  social:
    facebook:
      app-id: 2010494489235858
      app-secret: 5bb40c366ad19825d34fa868b6ed2947
    twitter:
      app-id: VroWfn8ooSQTFpCLne1OYoRKg
      app-secret: T6bfvTBioRkyfj32kW8qw4ar5UBAX1W5G2UZGogyl2cvHpBV2l
    linkedin:
      app-id: 77dvneln1s4ne1
      app-secret: vY2FrdxJl8wMPGb8
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my-spring-social
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create

